import React, { useState } from 'react';
import { Button, Alert } from 'react-bootstrap';
import 'bootstrap/dist/css/bootstrap.min.css'; // Import Bootstrap CSS
import './addAssetModel.css'; // Assuming you have a CSS file for styling
import { API_URLS } from '../../../declarations/apiConfig';

const AddAssetModel = () => {
    const [modelName, setModelName] = useState('');
    const [showSuccessAlert, setShowSuccessAlert] = useState(false);
    const [showErrorAlert, setShowErrorAlert] = useState(false);

    const handleSubmit = (e) => {
        e.preventDefault();

        const newAssetModel = {
            id: 0, // Adjust if ID is generated by the server
            modelName
        };

        fetch(API_URLS.ASSET.ADD_NEW_MODEL, {
            method: 'POST',
            credentials: 'include',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(newAssetModel)
        })
            .then(response => {
                if (!response.ok) {
                    throw new Error('Network response was not ok');
                }
                return response.json();
            })
            .then(() => {
                setShowSuccessAlert(true);
                setModelName(''); // Clear input field after successful submission
            })
            .catch(error => {
                console.error('Error adding asset model:', error);
                setShowErrorAlert(true);
            });
    };

    return (
        <div className="mt-5 d-flex justify-content-center">
            <div className="card p-5 shadow-lg" style={{ maxWidth: "700px", borderRadius: "10px" }}>
                <h1 id="asset-model-title" className="text-center mb-5">Agregar Modelo de Activo</h1>
                
                <form onSubmit={handleSubmit}>
                    <div className="mb-4 row align-items-center">
                        <label htmlFor="modelName" id="label-modelName" className="col-sm-4 col-form-label form-label">
                            <i className="fas fa-cogs" id="icon-modelName"></i> Nombre del Modelo
                        </label>
                        <div className="col-sm-8 w-100 mb-4">
                            <input
                                type="text"
                                id="modelName"
                                className="form-control border-primary"
                                placeholder="Ingresa el nombre del modelo"
                                value={modelName}
                                onChange={(e) => setModelName(e.target.value)}
                                required
                            />
                        </div>
                    </div>
                    <div className="text-center">
                        <Button className="btn btn-lg btn-custom w-100 shadow-sm" type="submit">
                            <i className="fas fa-save"></i> Guardar
                        </Button>
                    </div>
                </form>
    
                {/* Success Alert */}
                {showSuccessAlert && (
                    <div className="alert alert-success mt-4 text-center" role="alert">
                        Modelo de activo ingresado correctamente!
                    </div>
                )}
    
                {/* Error Alert */}
                {showErrorAlert && (
                    <div className="alert alert-danger mt-5 text-center" role="alert">
                        Se produjo un error al agregar el modelo de activo. Por favor inténtalo de nuevo.
                    </div>
                )}
            </div>
        </div>
    );
};

export default AddAssetModel;
